language: node_js
node_js:
  - 0.8
sass:
  - 3.2
coffee:
  - 1.3.3
compass:
  - 0.12
before_install:
  - gem install sass
  - gem install compass
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  webhooks:
    - https://www.buildheroes.com/api/projects/6273fa77e155d17a761cd409270db2fcdf797b8f/builds